// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMIS.Data;

#nullable disable

namespace RMIS.Migrations
{
    [DbContext(typeof(MapDBContext))]
    [Migration("20250401094022_add dataInfo in pipeline")]
    partial class adddataInfoinpipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMIS.Models.sql.AdminDist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminDist");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminDistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminDistId");

                    b.HasIndex("LayerId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RMIS.Models.sql.ConstructNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdministrativeDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfterConstructionPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeConstructionPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConstructionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConstructionLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionScope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConstructionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConstructionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaytimeConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NighttimeConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrafficControlPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConstructNotices");
                });

            modelBuilder.Entity("RMIS.Models.sql.GeometryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Svg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeometryTypes");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeometryTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeometryTypeId");

                    b.HasIndex("PipelineId");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("RMIS.Models.sql.MapSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MapSources");
                });

            modelBuilder.Entity("RMIS.Models.sql.MetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayScale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayerCoverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MetadataUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvidingUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceSystemInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetaDatas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGeneralPipeline")
                        .HasColumnType("bit");

                    b.Property<string>("ManagementUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MetaDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MetaDataId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("RMIS.Models.sql.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdministrativeDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompensationBudget")
                        .HasColumnType("int");

                    b.Property<int>("ConstructionBudget")
                        .HasColumnType("int");

                    b.Property<long>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("DATEDIFF(SECOND, '1970-01-01', GETUTCDATE())");

                    b.Property<string>("CurrentRoadWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("LandAcquisitionBudget")
                        .HasColumnType("int");

                    b.Property<Guid>("PlannedExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlannedRoadWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrivateLand")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicLand")
                        .HasColumnType("int");

                    b.Property<int>("PublicPrivateLand")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RoadLength")
                        .HasColumnType("real");

                    b.Property<string>("StartEndLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StreetViewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalBudget")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoadProjects");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.HasOne("RMIS.Models.sql.AdminDist", "AdminDist")
                        .WithMany()
                        .HasForeignKey("AdminDistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMIS.Models.sql.Layer", "Layer")
                        .WithMany("Areas")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminDist");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.HasOne("RMIS.Models.sql.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.HasOne("RMIS.Models.sql.GeometryType", "GeometryType")
                        .WithMany("Layers")
                        .HasForeignKey("GeometryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMIS.Models.sql.Pipeline", "Pipeline")
                        .WithMany("Layers")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeometryType");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.HasOne("RMIS.Models.sql.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMIS.Models.sql.MetaData", "MetaData")
                        .WithMany()
                        .HasForeignKey("MetaDataId");

                    b.Navigation("Category");

                    b.Navigation("MetaData");
                });

            modelBuilder.Entity("RMIS.Models.sql.Point", b =>
                {
                    b.HasOne("RMIS.Models.sql.Area", "Area")
                        .WithMany("Points")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("RMIS.Models.sql.GeometryType", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
