// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RMIS.Data;

#nullable disable

namespace RMIS.Migrations
{
    [DbContext(typeof(MapDBContext))]
    [Migration("20260512011129_RoadProjectAllFieldsNullable")]
    partial class RoadProjectAllFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accident101", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_101", (string)null);
                });

            modelBuilder.Entity("Accident102", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_102", (string)null);
                });

            modelBuilder.Entity("Accident103", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_103", (string)null);
                });

            modelBuilder.Entity("Accident104", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_104", (string)null);
                });

            modelBuilder.Entity("Accident105", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_105", (string)null);
                });

            modelBuilder.Entity("Accident106", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_106", (string)null);
                });

            modelBuilder.Entity("Accident107", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_107", (string)null);
                });

            modelBuilder.Entity("Accident108", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_108", (string)null);
                });

            modelBuilder.Entity("Accident109", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_109", (string)null);
                });

            modelBuilder.Entity("Accident110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_110", (string)null);
                });

            modelBuilder.Entity("Accident111", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_111", (string)null);
                });

            modelBuilder.Entity("Accident112", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_112", (string)null);
                });

            modelBuilder.Entity("Accident113", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alley");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("areacode");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("countycode");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("IntersectionAlley")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_alley");

                    b.Property<string>("IntersectionLane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_lane");

                    b.Property<string>("IntersectionRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_road");

                    b.Property<string>("IntersectionSection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intersection_section");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lane");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_type");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longitude");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road");

                    b.Property<string>("RoadOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("road_other");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("accident_113", (string)null);
                });

            modelBuilder.Entity("RMIS.Models.sql.AdminDist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminDist");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminDistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminDistId");

                    b.HasIndex("LayerId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RMIS.Models.sql.ConstructNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdministrativeDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfterConstructionPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeConstructionPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConstructionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConstructionLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionScope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConstructionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConstructionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaytimeConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NighttimeConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrafficControlPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConstructNotices");
                });

            modelBuilder.Entity("RMIS.Models.sql.GeometryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Svg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeometryTypes");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeometryTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImportEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeometryTypeId");

                    b.HasIndex("PipelineId");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("RMIS.Models.sql.MapSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MapSources");
                });

            modelBuilder.Entity("RMIS.Models.sql.MetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayScale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayerCoverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MetadataUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvidingUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceSystemInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetaDatas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGeneralPipeline")
                        .HasColumnType("bit");

                    b.Property<string>("ManagementUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("RMIS.Models.sql.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Geometry>("GeoLocation")
                        .HasColumnType("geography");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("RMIS.Models.sql.ProcessEditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("process_edit_log");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProject", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdministrativeDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompensationBudget")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionBudget")
                        .HasColumnType("int");

                    b.Property<bool?>("CoordinateChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentRoadWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Index"));

                    b.Property<int?>("LandAcquisitionBudget")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlannedExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlannedRoadWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicPrivateLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RCCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoadLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartEndLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StreetViewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TinHouseCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalBudget")
                        .HasColumnType("int");

                    b.Property<string>("step")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoadProjects");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProjectProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementCommencementDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicDesignApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetFiscalYearApprovedAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionExecution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignDispatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedDesignApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpropriationApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpropriationPlanPreReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpropriationPlanSubmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketPriceReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegotiatedPurchaseMeeting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PreviousMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousMeetingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicHearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("road_project_process");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProjectProcess1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstructionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PreviousMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousMeetingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("road_project_process_1");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProjectProcess2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PreviousMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousMeetingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("road_project_process_2");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProjectProcess3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementCommencementDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetFiscalYearApprovedAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PreviousMeetingResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousMeetingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("road_project_process_3");
                });

            modelBuilder.Entity("RMIS.Models.sql.RoadProjectProcessFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64String")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UploadUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoadProjectProcessFiles");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.HasOne("RMIS.Models.sql.AdminDist", "AdminDist")
                        .WithMany()
                        .HasForeignKey("AdminDistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMIS.Models.sql.Layer", "Layer")
                        .WithMany("Areas")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminDist");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.HasOne("RMIS.Models.sql.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.HasOne("RMIS.Models.sql.GeometryType", "GeometryType")
                        .WithMany("Layers")
                        .HasForeignKey("GeometryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMIS.Models.sql.Pipeline", "Pipeline")
                        .WithMany("Layers")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeometryType");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.HasOne("RMIS.Models.sql.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RMIS.Models.sql.Point", b =>
                {
                    b.HasOne("RMIS.Models.sql.Area", "Area")
                        .WithMany("Points")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RMIS.Models.sql.Area", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("RMIS.Models.sql.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("RMIS.Models.sql.GeometryType", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("RMIS.Models.sql.Layer", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("RMIS.Models.sql.Pipeline", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
